# Generated by Django 4.1.5 on 2023-01-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_doctors'),
        ('doctors', '0003_remove_doctor_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(null=True, to='patients.patient'),
        ),
    ]
