# Generated by Django 4.1.5 on 2023-01-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_doctors'),
        ('doctors', '0004_doctor_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(to='patients.patient'),
        ),
    ]
