# Generated by Django 4.1.5 on 2023-01-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_doctors'),
        ('doctors', '0005_alter_doctor_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(null=True, to='patients.patient'),
        ),
    ]
